### ISSUE TITLE
NUL fails to compile with gcc-4.9.0

### ISSUE THREAD

**Issue by udosteinberg** [TUD-OS/NUL#19]
```
bin/lib/libservice.a(hostsink.o): In function `DBus<MessageSerial>::set_size(unsigned int)':
/home/git/nul/base/include/nul/bus.h:62: undefined reference to `__cxa_throw_bad_array_new_length'
bin/lib/libservice.a(kbd2serial.o): In function `DBus<MessageInput>::set_size(unsigned int)':
/home/git/nul/base/include/nul/bus.h:62: undefined reference to `__cxa_throw_bad_array_new_length'
bin/lib/libservice.a(serial2kbd.o): In function `DBus<MessageSerial>::set_size(unsigned int)':
/home/git/nul/base/include/nul/bus.h:62: undefined reference to `__cxa_throw_bad_array_new_length'
bin/lib/libservice.a(service_disk.o): In function `DBus<MessageDiskCommit>::set_size(unsigned int)':
/home/git/nul/base/include/nul/bus.h:62: undefined reference to `__cxa_throw_bad_array_new_length'
```

Older compilers up to and including 4.8.0 work fine.
